### ISSUE TITLE
Postgres 12 support

### ISSUE THREAD

**Issue by Coffei** [pjungwir/range_agg#1] opened 2020-04-15 14:09 UTC
Hi,
I am having problems using this extension in Postgres 12. Compilation seems to be successful (although some warnings are emitted, see below). However, enabling the extension with `CREATE EXTENSION IF NOT EXISTS range_agg;` fails with
```
ERROR:  could not load library "/usr/lib/postgresql/12/lib/range_agg.so": /usr/lib/postgresql/12/lib/range_agg.so: undefined symbol: RangeTypeGetDatum
```

I am compiling the extension in the official postgres docker image.
Compilation produces these warnings
```
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -I. -I./ -I/usr/include/postgresql/12/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o range_agg.o range_agg.c
range_agg.c: In function ‘range_agg_finalfn’:
range_agg.c:107:15: warning: implicit declaration of function ‘DatumGetRangeType’; did you mean ‘DatumGetRangeTypeP’? [-Wimplicit-function-declaration]
   lastRange = DatumGetRangeType(inputVals[0]);
               ^~~~~~~~~~~~~~~~~
               DatumGetRangeTypeP
range_agg.c:107:13: warning: assignment to ‘RangeType *’ {aka ‘struct <anonymous> *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
   lastRange = DatumGetRangeType(inputVals[0]);
             ^
range_agg.c:110:18: warning: assignment to ‘RangeType *’ {aka ‘struct <anonymous> *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
     currentRange = DatumGetRangeType(inputVals[i]);
                  ^
range_agg.c:127:39: warning: implicit declaration of function ‘RangeTypeGetDatum’; did you mean ‘RangeTypePGetDatum’? [-Wimplicit-function-declaration]
       accumArrayResult(resultContent, RangeTypeGetDatum(lastRange), false, rangeTypeId, aggContext);
                                       ^~~~~~~~~~~~~~~~~
                                       RangeTypePGetDatum
range_agg.c:80:9: warning: variable ‘inputNulls’ set but not used [-Wunused-but-set-variable]
   bool *inputNulls;
         ^~~~~~~~~~
range_agg.c: In function ‘element_compare’:
range_agg.c:155:19: warning: initialization of ‘RangeType *’ {aka ‘struct <anonymous> *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
   RangeType *r1 = DatumGetRangeType(*d1);
                   ^~~~~~~~~~~~~~~~~
range_agg.c:156:19: warning: initialization of ‘RangeType *’ {aka ‘struct <anonymous> *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
   RangeType *r2 = DatumGetRangeType(*d2);
                   ^~~~~~~~~~~~~~~~~
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC range_agg.o -L/usr/lib/x86_64-linux-gnu -Wl,-z,relro -Wl,-z,now -L/usr/lib/llvm-7/lib  -L/usr/lib/x86_64-linux-gnu/mit-krb5 -Wl,--as-needed  -shared -o range_agg.so
/usr/bin/clang-7 -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I. -I./ -I/usr/include/postgresql/12/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5 -flto=thin -emit-llvm -c -o range_agg.bc range_agg.c
range_agg.c:107:15: warning: implicit declaration of function 'DatumGetRangeType' is invalid in C99 [-Wimplicit-function-declaration]
  lastRange = DatumGetRangeType(inputVals[0]);
              ^
range_agg.c:107:13: warning: incompatible integer to pointer conversion assigning to 'RangeType *' from 'int' [-Wint-conversion]
  lastRange = DatumGetRangeType(inputVals[0]);
            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
range_agg.c:110:18: warning: incompatible integer to pointer conversion assigning to 'RangeType *' from 'int' [-Wint-conversion]
    currentRange = DatumGetRangeType(inputVals[i]);
                 ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
range_agg.c:127:39: warning: implicit declaration of function 'RangeTypeGetDatum' is invalid in C99 [-Wimplicit-function-declaration]
      accumArrayResult(resultContent, RangeTypeGetDatum(lastRange), false, rangeTypeId, aggContext);
                                      ^
range_agg.c:142:35: warning: implicit declaration of function 'RangeTypeGetDatum' is invalid in C99 [-Wimplicit-function-declaration]
  accumArrayResult(resultContent, RangeTypeGetDatum(lastRange), false, rangeTypeId, aggContext);
                                  ^
range_agg.c:155:19: warning: implicit declaration of function 'DatumGetRangeType' is invalid in C99 [-Wimplicit-function-declaration]
  RangeType *r1 = DatumGetRangeType(*d1);
                  ^
range_agg.c:155:14: warning: incompatible integer to pointer conversion initializing 'RangeType *' with an expression of type 'int' [-Wint-conversion]
  RangeType *r1 = DatumGetRangeType(*d1);
             ^    ~~~~~~~~~~~~~~~~~~~~~~
range_agg.c:156:14: warning: incompatible integer to pointer conversion initializing 'RangeType *' with an expression of type 'int' [-Wint-conversion]
  RangeType *r2 = DatumGetRangeType(*d2);
             ^    ~~~~~~~~~~~~~~~~~~~~~~
8 warnings generated.
```

Any chance you could look at it?
Thank you!

**Comment by pjungwir** [comment] 2020-04-15 15:51
Thanks for the report! This was caused by a couple macros that were renamed in Postgres 11. I've pushed a fix and also uploaded a new version to pgxn (in case you're getting it from there). Let me know if you continue to have any trouble!

**Closed as completed by pjungwir** 2020-04-15 15:51 UTC

**Comment by Coffei** [comment] 2020-04-15 16:05
Thanks for such a speedy fix! Will let you know if I encounter any more problems.

**Comment by Coffei** [comment] 2020-04-16 12:09
@pjungwir Now `make install` fails with the following error
```
/usr/bin/install: cannot stat './/range_agg--1.2.0.sql': No such file or directory
```

I think the file is named incorrectly, there's missing dash, now its `range_agg-1.2.0.sql`

**Comment by Coffei** [comment] 2020-04-16 12:13
Submited PR for the change https://github.com/pjungwir/range_agg/pull/2
